server:
    port : 9090
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springbootcourse?serverTimezone=UTC
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        
